# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160211_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='slug',
            field=models.CharField(default='slug', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
