# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='short',
            field=models.TextField(default='Short Description'),
            preserve_default=False,
        ),
    ]
